# -*- coding: utf-8 -*-
"""trabajo_con_print.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xDroX89SAW2jTL71bd2kZaalz5t6e7iF
"""

####codigo de prueba:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
def Columns(df):
  columnas = df.columns
  list_columns = list(columnas)
  return list_columns
 
   #Empieza el programa:
print("Ingrese la ruta de acceso de la base de datos a trabajar en formato excel: ")
base_datos=input("Ingrese aqui la  ruta de acceso a trabajar: ")
archivo_df1 = pd.read_excel(base_datos)
print("Que desea hacer?" )
respuesta = input("1) Ingresar datos a la base de datos y que se actualicen\n2) Filtrar datos por medio de características\n3) Solicitar gráficos de análisis entre algunas variables\n4) Solicitar datos estadísticos de los datos\n5) Generar nuevas características para los datos. (Nuevas columnas)\n6) Salir del programa\n Escriba el numero a eleccion: ")
while True:
  if respuesta=="1":
    dicc_fila = {}
    columnas_df = Columns(archivo_df1) # Retorna una lista con las columnas
    print(columnas_df)
    for i in columnas_df:
      dicc_fila[i] = input('Ingrese valor de la columna {} '.format(i))
    archivo_df1 = archivo_df1.append(dicc_fila, ignore_index = True)
    for i in columnas_df:
      tipo=type(archivo_df1[i][0])   
      if tipo==int:
        archivo_df1[i][len(archivo_df1)-1]=int( archivo_df1[i][len(archivo_df1)-1])
    archivo_df1.to_excel(base_datos, index= False )
    print("-"*200)
    respuesta=input("Escriba el numero a su eleccion y si quiere salir, oprima '6': ")    
  elif respuesta=="2":
    variable = input("Desea filtrar 'palabras', 'numeros' o un 'intervalo': " )
    columnas_df = Columns(archivo_df1) # Retorna una lista con las columnas
    print("Las columnas son: ",columnas_df)
    filtro = input("Escribe la columna a filtrar: ")
    if variable == "palabras" or variable=="PALABRAS":
      palabra=input("Escribe el dato a filtrar: ")
      respuesta =archivo_df1.loc[archivo_df1[filtro] == palabra]
      print(respuesta)
    elif variable == "numeros" or variable =="NUMEROS":
      palabra = float(input("Escribe el dato a filtrar: "))
      respuesta =archivo_df1.loc[archivo_df1[filtro] == palabra]
      print(respuesta)
    elif variable == "intervalo" or variable == "INTERVALO":
      print("Escriba 'R' si desea ingresar un rango,")
      print("Escriba '<' si desea valores menores que...,")
      print("Escriba '>' si desea valores mayores que...,")
      decision = input()
      if decision == 'R':
        v_min = float(input('Ingrese el valor mínimo: '))
        v_max = float(input('Ingrese el valor máximo: '))
        respuesta = archivo_df1.loc[(archivo_df1[filtro] > v_min) & (archivo_df1[filtro] < v_max)]
        print(respuesta)
      elif decision == '<':
        menores = float(input('Ingrese {} para mostrar los valores menores: '.format(filtro)))
        respuesta = archivo_df1.loc[archivo_df1[filtro] < menores]
        print(respuesta)
      elif decision == '>':
        mayores = float(input('Ingrese {} para mostrar los valores mayores: '.format(filtro)))
        respuesta = archivo_df1.loc[archivo_df1[filtro] > mayores]
        print(respuesta)
    print("-"*200)
    respuesta=input("Escriba el numero a su eleccion y si quiere salir, oprima '6': ")
  elif respuesta=="3":
    print("Escriba 'd' si quiere trabajar con graficos de dispersion \nEscriba 'h' si quiere trabajar con histogramas: ")
    respuesta5=input("Escriba aqui su respuesta: ")
    columnas_df = Columns(archivo_df1) # Retorna una lista con las columnas
    print("Las variables son: ",columnas_df)
    variable_contador=int(input("Ingrese la cantidad de graficos a analizar: "))
    if respuesta5=="d" :
      cont=0
      while cont<variable_contador:
        var_x=input("Ingresa la variable X a utilizar: ")
        var_y=input("Ingresa la variable Y a utilizar: ")
        archivo_df1.plot(subplots=True,kind="scatter",x = var_x,y=var_y, alpha=0.5, cmap= "viridis")
        cont+=1
        plt.show()
    elif respuesta5=="h" :
      cont=0
      while cont<variable_contador:
        palabra=list(archivo_df1[input("Elija la variable a analizar: ")])
        plt.style.use("seaborn-white")
        palabra_array=np.array(palabra)
        plt.hist(palabra_array, bins=10, alpha=0.5,histtype="bar", color="steelblue", edgecolor= "black")
        cont+=1
        plt.show()
    print("-"*200)
    respuesta=input("Escriba el numero a su eleccion y si quiere salir, oprima '6': ")
  elif respuesta=="4":
    columnas_df = Columns(archivo_df1) # Retorna una lista con las columnas
    print("Las variables son: ",columnas_df)
    Estadistica_var = input('ingrese valor a evaluar: ')
    Estadistica_indiv = archivo_df1[Estadistica_var].describe()
    print(Estadistica_indiv)
    print("-"*200)    
    respuesta=input("Escriba el numero a su eleccion y si quiere salir, oprima '6': ")
  elif respuesta == "5":
    datos_fila = []
    nueva_columna = input('Ingrese nombre de la nueva columna: ')
    numero_letra = input("Escriba 'N' si desea ingresar datos numericos o 'L' si desea ingresar cadena de texto en la columna: ")
    if numero_letra == 'n' or numero_letra == 'N':
      calculo = input("Escriba 'M' para ingresar los datos manualmente o 'C' para hacer calculos matemáticos automaticos usando otras columnas: ")
      if calculo == 'C':
        print('Qué operación desea realizar en la columna {}:'.format(nueva_columna))
        print("1) Sumar \n2) Multiplicar \n3) Promediar")
        operacion = input('Escriba el número para realizar la operación: ')
        if operacion == '1':
          columna_suma = []
          numero_columna = int(input('Escriba la cantidad de columnas que desea sumar: '))
          columnas_df = Columns(archivo_df1) 
          print("Las columnnas son: ",columnas_df)
          for k in range(1,numero_columna+1):
            nombre_columna = input('Ingrese el nombre de la columna {}: '.format(k))
            columna_suma.append(nombre_columna)
          for i in range(0, len(archivo_df1)):
            sumar_columnas = 0
            for j in range(0, len(columna_suma)):
              sumar_columnas = sumar_columnas + archivo_df1[columna_suma[j]][i]
            datos_fila.append(sumar_columnas)
        elif operacion == '2':
          print('Qué columnas desea multiplicar: ')
          columna_producto = []
          numero_columna = int(input('Escriba la cantidad de columnas que desea multiplicar: '))
          columnas_df = Columns(archivo_df1) 
          print("Las columnnas son: ",columnas_df)
          for k in range(1,numero_columna+1):
            nombre_columna = input('Ingrese el nombre de la columna {}: '.format(k))
            columna_producto.append(nombre_columna)
          for i in range(0, len(archivo_df1)):
            multiplicar_columnas = 1
            for j in range(0, len(columna_producto)):
              multiplicar_columnas = multiplicar_columnas*archivo_df1[columna_producto[j]][i]
            datos_fila.append(multiplicar_columnas)
        if operacion == '3':
          columna_promedio = []
          numero_columna = int(input('Escriba la cantidad de columnas que desea promediar: '))
          columnas_df = Columns(archivo_df1) 
          print("Las columnnas son: ",columnas_df)
          for k in range(1,numero_columna+1):
            nombre_columna = input('Ingrese el nombre de la columna {}: '.format(k))
            columna_promedio.append(nombre_columna)
          for i in range(0, len(archivo_df1)):
            sumar_columnas = 0
            for j in range(0, len(columna_promedio)):
              sumar_columnas = sumar_columnas + archivo_df1[columna_promedio[j]][i]
            promedio = sumar_columnas/len(columna_promedio)
            prom = round(promedio,2)
            datos_fila.append(prom)
      elif calculo == 'M':
        print('Ingrese los datos de la columna {} y presione [enter] para continuar:'.format(nueva_columna))
        for i in range(0,len(archivo_df1)):
          columnas_df = Columns(archivo_df1)
          primera_columna= columnas_df[0]
          id_variable = archivo_df1[primera_columna][i]
          ingresar_dato = int(input("Ingresar el valor de {} {}: ".format(primera_columna,  id_variable)))
          datos_fila.append(ingresar_dato)
    elif numero_letra == 'L' or numero_letra == 'l':
      print('Ingrese los datos de la columna {} y presione [enter] para continuar:'.format(nueva_columna))
      for i in range(0,len(archivo_df1)):
        columnas_df = Columns(archivo_df1)
        primera_columna = columnas_df[0]
        id_variable = archivo_df1[primera_columna][i]
        ingresar_dato = input("Ingresar el valor de {} {}: ".format(primera_columna,  id_variable))
        datos_fila.append(ingresar_dato)
    archivo_df1[nueva_columna] = datos_fila
    archivo_df1.to_excel(base_datos, index = False)
    print(archivo_df1)
    print("-"*200)
    respuesta=input("Escriba el numero a su eleccion y si quiere salir, oprima '6': ")
  elif respuesta=="6":
    print("Gracias por usar nuestro programa")
    print("-"*200)
    break
  else:
     print("-"*200) 
     respuesta=input("Escriba el numero a su eleccion y si quiere salir, oprima '6': ")

from google.colab import drive
drive.mount('/content/drive')